### ISSUE TITLE
[FEATURE] Add support for timezones

### ISSUE THREAD

**Issue by les2** [mydea/ember-date-components#1]
Occasionally  it is useful to display a date picker in a different timezone than the current user's. It mainly affects the current today value.

**Comment by mydea** [comment]
Hmm, I'm not quite sure how this should look/work. There could potentially be a select box in the options menu which allows selection of a timezone. However, I fear that this would introduce quite some complexity there. While I don't really have time for this right now, I would be happy to review a PR.

**Comment by les2** [comment]
I agree that it is "stupid" but I have seen this requirement in the wild.

The legacy app I'm currently porting does something quite "evil" (IMO): The date-picker is displayed in the current user's tz *but* the value is "interpreted" as being in the account timezone. No visual indication of this is rendered!!! How awful, right?

Example
-----------
If you're dealing with, say Facebook business manager, there is this "concept" of an `account timezone`. If your client's account is setup as PT, then when they say, "this ad should go live at 3 PM", it means "3 PM" in PT. Your ad management people are of course in NY. One can imagine the confusion.

What FB does in their UI is *always* display the timezone along with the datepicker.
-------------------------

I hear you on the complexity and no-time-for-that issues.

I'd like to contribute a PR for this when I get to this feature in the app I'm porting: I'll have to implement it one way or another. I've been doing some reconnaissance on ember datepickers and this component looked great which I was I opened this issue eagerly.

**Comment by mydea** [comment]
Thanks for the detailed feedback :)

I think going the FB way and just displaying the currently selected timezone could be an easy fix. However, it has to be done in a way that the datepicker still works without moment-timezones included - which shouldn't be that hard, I guess. We could just (optionally) show the timezone (e.g. "America/Los Angeles") over the buttons. What do you mean, would that work for you?

**Comment by mydea** [comment]
I'm closing this for now for lack of feedback - feel free to re-open it if appropriate :)
