### ISSUE TITLE
yarn.lock contains unaccessible URL

### ISSUE THREAD

**Issue by mixonic** [mydea/ember-date-components#11]
The URLs in https://github.com/mydea/ember-date-components/blob/master/yarn.lock#L7 are not publicly accessible. It seems like the lock file should point at public URLs, or contributors will not be able to install dependencies.

**Comment by mydea** [comment]
Uh, good catch. We use a proxy repository which mirrors from NPM, and it seems I forgot to turn it off here. Thanks!
