### ISSUE TITLE
Dates are shown in the wrong weekday.

### ISSUE THREAD

**Issue by alejandrodevs** [mydea/ember-date-components#135]
In  ember cli 3.17.0 I'm getting the dates in the wrong weekday.

May should finish on Sunday.
<img width="292" alt="Captura de Pantalla 2020-06-03 a la(s) 21 01 04" src="https://user-images.githubusercontent.com/1541261/83706505-44de5b80-a5dd-11ea-904e-9fcd405887c8.png">

Jun starts in the correct weekday:
<img width="289" alt="Captura de Pantalla 2020-06-03 a la(s) 20 59 32" src="https://user-images.githubusercontent.com/1541261/83706517-50318700-a5dd-11ea-86c4-fff9fe9a4c62.png">

But july starts in a wrong weekday:
<img width="290" alt="Captura de Pantalla 2020-06-03 a la(s) 20 59 49" src="https://user-images.githubusercontent.com/1541261/83706535-60e1fd00-a5dd-11ea-9c25-98b2b7ed6a1d.png">

**Comment by mydea** [comment]
Can you try with the current master branch? (so in your package.json e.g.: `"ember-date-components": "mydea/ember-date-components#master"`). I made some adjustments recently to fix some issues in that area, but haven't made a release yet. If it works fine for you, I will cut a release!

**Comment by alejandrodevs** [comment]
Yes, it is working good from master branch. Could you please release a new version?

**Comment by mydea** [comment]
Fixed and released in 2.1.0!
