### ISSUE TITLE
Error in 2.1.0 with min & max value 

### ISSUE THREAD

**Issue by dmaok** [mydea/ember-date-components#137]
How to reproduce:

- git clone https://github.com/mydea/ember-date-components.git
- cd ember-date-components
- yarn install
- ember serve
- visit http://localhost:4200/usage/date-picker
- Click "Select Date" in "With min & max value" section

error:
<img width="623" alt="Screenshot 2020-06-10 at 15 55 39" src="https://user-images.githubusercontent.com/16311938/84270116-da747080-ab32-11ea-938f-c0dacc3b6f3d.png">

**Comment by mydea** [comment]
Fixed in v2.1.2 - thank you!
