### ISSUE TITLE
Localizations

### ISSUE THREAD

**Issue by GELight** [mydea/ember-date-components#14]
Hi,

2 Questions:

1. Is there a possibillity to localize only all texts without write an option with all params?
2. Can I add some customized css class names for the picker buttons? ( e.g. Bootstrap "btn btn-primary" )

Best regards,
Mario

**Comment by mydea** [comment]
Hey,

regarding 1., in our app we extend the date-picker component and overwrite the `_optionsMap` like this:

```js
  _optionsMap: computed(function() {
    let l10n = get(this, 'l10n');

    return {
      'clear': {
        action: 'clearDate',
        label: l10n.t('Clear'),
        classes: ''
      },
      'today': {
        action: 'selectToday',
        label: l10n.t('Today'),
        classes: 'button--light'
      },
     // ...
    };
  })
```

This way, they are localized by default. In the same way, you can localize all other texts to fit your needs.

Regarding 2.), this is documented here: http://mydea.github.io/ember-date-components/#/usage/date-picker - see `buttonClasses`. Or, if you mean the option buttons, see the above example, where you can also add classes to them.
