### ISSUE TITLE
Ember power select breaks this addon

### ISSUE THREAD

**Issue by roncodes** [mydea/ember-date-components#144]
Using this addon along with ember-power-select causes ember-date-components to fail to render.

**Comment by mydea** [comment]
How does it break? We have been using this alongside ember-power-select, but maybe an older version.

**Comment by roncodes** [comment]
Actually I'm thinking it's because they are trying to share the same wormhole, I'm not sure.

I did create a new ember octane project, and if i install `ember-date-components` and use the basic usage it works fine. but after installing `ember-power-select` the `<DatePicker />` doesn't display at all.

**Comment by mydea** [comment]
Could you spin up a reproduction somewhere in a repo, then I'll happily check it out to see if I can find the issue!

**Comment by roncodes** [comment]
I setup a repo here https://github.com/roncodes/octane-date-components-test

It's octane 3.18 + ember-date-components and ember-power-select

**Comment by mydea** [comment]
This was due to ember-power-select requiring ember-basic-dropdown 3.x, and this addon using 1.x. I have updated this, and will make a major release (3.0) of this addon with this change soon!
