### ISSUE TITLE
Prettier run messed up Ember.get calls

### ISSUE THREAD

**Issue by mlb5000** [mydea/ember-date-components#152]
It looks like a prettier run messed up a bunch of Ember.get calls. This appears to be the case with every release after v2.0.6. An example is in `time-picker.js`. 

After Prettier:
https://github.com/mydea/ember-date-components/blob/f532d9459bc11105e7752b2d056732cab48d6ea4/addon/components/time-picker.js#L329

Before Prettier:
https://github.com/mydea/ember-date-components/commit/36e29c200692c5933368aaaabc674206e6e0153b#diff-dd2ea6f43e83040327c685e5bbcc1753L321

As you can see this:

```
    let value = get(this, 'value');
    let format = get(this, 'format');
```

Was changed to this:

```
let { value, format } = this;
```

I don't believe this type of object destructuring works for accessing Ember properties...at least not that I'm aware of, and not in my version of Ember, which causes various things to break if I upgrade beyond v2.0.6.

**Comment by mydea** [comment]
Hey,  in newer versions of Ember (I believe 3.4+, but not sure), this is perfectly valid!

Sorry for not making a major version right then, I kind of forgot. Stick to `~2.0.6` if you cannot update Ember yet!

**Comment by mlb5000** [comment]
@mydea Ya I was hesitant to outright say "that's not valid" since it seemed strange that prettier would understand Ember's get call well enough to transform it in that way, yet so incorrectly as to break usages of it, lol. That's good to know for later Ember versions though.
