### ISSUE TITLE
Addon doesn't work for me

### ISSUE THREAD

**Issue by alexborovkov** [mydea/ember-date-components#17]
I've got  TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.

**Comment by AleksandrBorovkov** [comment]
I've installed ember-basic-dropdown and error gone. But when I select some value in calendar, input value doesn't update.
I use default config
`{{date-picker range=true action=(action 'updateDate')}}`

**Comment by AleksandrBorovkov** [comment]
@mydea It seems that action 'updateDate' doesn't trigger

**Comment by AleksandrBorovkov** [comment]
I've set renderInPlace=true and this solve the problem.

**Comment by mydea** [comment]
None of this should really be necessary. ember-basic-dropdown should be included via the dependencies, and the action should normally work - I tried again in the dummy app, where everything works fine. Which versions of ember and ember-cli are you using?

**Comment by AleksandrBorovkov** [comment]
"ember-source": "2.13.3",
"ember-cli": "2.11.0",

Also I can't select month and year. I think this related to renderInPlace option too.  I suppose you need to transfer this option to inner `date-picker-month-year-select` and `date-picker-month` components.

**Comment by mydea** [comment]
Sadly, I really can't replicate this - does e.g. ember-power-select work for you?

**Comment by mydea** [comment]
No, I mean if other addons using ember-basic-dropdown work. Or if using ember-basic-dropdown directly works?

**Comment by stepanushariara** [comment]
Hi Guys,
I use ember-date-component but everytime i click it then always get errror like this picture.
How to solve this ??

<img width="591" alt="screen shot 2018-08-09 at 4 45 39 pm" src="https://user-images.githubusercontent.com/5647649/43891557-cd627658-9bf3-11e8-8a06-6c3bb6f090ca.png">

**Comment by mydea** [comment]
Can you tell me:

1. What version of ember-date-components you are using
2. What version of ember-basic-dropdown you are using (if you use yarn, you can find the exact version in the yarn.lock file, or you could just look into your node_modules folder and search for it there, in the package.json file you'll see the version)
3. Anything special about your env? How you start it, which environment (development/test/...)?

Also, does this code work for you, if you put it in a template:

```hbs
{{#basic-dropdown as |dropdown|}}
  {{#dropdown.trigger}}Click me{{/dropdown.trigger}}
  {{#dropdown.content}}Content of the trigger{{/dropdown.content}}
{{/basic-dropdown}}
```

**Comment by stepanushariara** [comment]
1. I use ember-date-component 1.1.2

2. In my package.json there is no ember-basic-dropdown
But, in package-lock.json there is ember-basic-dropdown 0.34.0 as a dependency of ember-date-component

3. I just use default setting ember.

Not yet, let me try

**Comment by mydea** [comment]
This addon depends on ember-basic-dropdown 1.x (which is also in its dependencies) - maybe some other addon or similar uses ember-basic-dropdown 0.34? I guess this could lead to this issue.

**Comment by stepanushariara** [comment]
So what should i do?

Should i install ember-basic-dropdown by package.json or modified the dependencies by package-lock.json??

**Comment by stepanushariara** [comment]
After i upgrade to version 1.1.5 (ember-basic-dropdown 1.0.0) then i got error like this when i click it

<img width="567" alt="screen shot 2018-08-10 at 12 13 57 pm" src="https://user-images.githubusercontent.com/5647649/43939897-0baad286-9c97-11e8-8195-f0d7d669af82.png">

**Comment by stepanushariara** [comment]
Dear mydea,

What i found in this addon is you missed to include ember-power-select.
without that it will showing error or missing html position.

after i added ember-power-select then nothing error and nothing miss html position.

**Comment by mydea** [comment]
Hmm, this does not depend on ember-power-select, but on ember-basic-dropdown.
I have an idea, though.

Could you try uninstalling ember-power-select and installing the `ensure-basic-dropdown-works` branch of this? (you can do this by setting the version in your package.json to `"mydea/ember-basic-dropdown#ensure-basic-dropdown-works"`)

I tried something there, let's see if it works!

**Comment by stepanushariara** [comment]
<img width="731" alt="screen shot 2018-08-23 at 7 06 09 pm" src="https://user-images.githubusercontent.com/5647649/44524442-c8c89b80-a707-11e8-85f4-38da73561889.png">


I've got error basic-dropdown in my server. there's nothing special settings in my Server.
Please advice..

**Comment by stepanushariara** [comment]
Still got same error..
