### ISSUE TITLE
time-picker button not updating after select

### ISSUE THREAD

**Issue by syedkhairi** [mydea/ember-date-components#182]
Hiya, the `time-picker` doesn't seem to update the placeholder or button text after the time is selected. Even on the demo website, it doesn't work (tested on Safari & Chrome). The `date-picker` works fine, where the button text changes to the selected date - but doesn't do the same for the time.

On top of that, I can't seem to get the `date-time-picker` to work. I can select the date, but it doesn't trigger to enable me to select the time. The time button remains disabled. 

Am I missing something here? Any ideas?

Thanks
S

**Comment by mydea** [comment]
It will only show the value passed in as `value`. So I suspect the problem is you are not passing the value in. This also goes for the date-time-picker - it expects a value to be passed in, to keep the data flow consistent.

**Comment by syedkhairi** [comment]
> It will only show the value passed in as `value`. So I suspect the problem is you are not passing the value in. This also goes for the date-time-picker - it expects a value to be passed in, to keep the data flow consistent.

Thank you! I managed to get it working now. I don't seem to have to do this for the `date-picker`.

Sharing what I did below in case anyone else in similar situation to mine previously!

template.hbs
```
<TimePicker @action={{this.addTime}} @placeholder="Select time" @value={{this.updateTimeButtonValue}} />
```

controller.js
```
import Component from '@glimmer/component';
import { inject as service } from '@ember/service';
import { tracked } from '@glimmer/tracking';
import { action } from '@ember/object';

export default class ExampleComponent extends Component {
  @tracked updateTimeButtonValue;

  @action
  addTime(time) {
    this.updateTimeButtonValue = time;
    //do something with time
  }
}
```
