### ISSUE TITLE
Cannot read property 'parentNode' of null

### ISSUE THREAD

**Issue by stepanushariara** [mydea/ember-date-components#19]
Hi guys,

I just got error Uncaught TypeError: Cannot read property 'parentNode' of null when everytime i click the component.

please give me solution

<img width="549" alt="screen shot 2018-08-09 at 4 51 12 pm" src="https://user-images.githubusercontent.com/5647649/43891850-90ebaa2c-9bf4-11e8-9827-c9c29d4bfdc3.png">

**Comment by mydea** [comment]
Closed in favor of #17
