### ISSUE TITLE
[FEATURE] Add support for languages

### ISSUE THREAD

**Issue by BennyAlex** [mydea/ember-date-components#2]
Can you ad support for different languages?

like 
`{{date-picker lang=''language" action=(action 'updateDateRange')}} `

or that I can set by my own the names of months and weekdays

```
let myOptions = [
{
  weekdays: ['mo', 'di', 'mi', 'do', 'fr', 'sa', 'so']
  months: ['Januar', 'Februar'/*...*/]
}];
```

**Comment by mydea** [comment]
It should just take the localized month/week names from moment.js. So there is no need to manually translate this.

See https://github.com/stefanpenner/ember-moment#i18n-support for how to configure the locale with ember-moment.
