### ISSUE TITLE
More options when range=true

### ISSUE THREAD

**Issue by noahgelman** [mydea/ember-date-components#28]
Could there be an option to remove or change the small dash between the 2 date-pickers? Maybe add an option to put a snippet of html between them with the dash as a default value? That way you can make it null to remove it all together or add something else.

And it would be nice if we could add 2 placeholders since there are 2 fields. A user can label them "Start Date" and "End Date" but currently are unable to do so.

**Comment by mydea** [comment]
For your first question, you can do that by specifying `dateRangeSeparator`, which defaults to `' - '`.

For the second point, yeah, I guess it would make sense to have an optional `placeholderTo` option. I would gladly accept a PR adding this option!
