### ISSUE TITLE
add support for selecting month, year

### ISSUE THREAD

**Issue by patricklx** [mydea/ember-date-components#3]
Hi,
It would be nice to have selectable months and years. Like here https://eternicode.github.io/bootstrap-datepicker
Any plans for this?

**Comment by mydea** [comment]
This is definitely something I want to do, but I first need to think about how this should look like. I'll keep you updated when I have made progress here!

**Comment by mydea** [comment]
This is now available in 1.0.0-beta.0. Please check it out and get back to me if you find any issues.

**Comment by mydea** [comment]
This is now in 1.0.0!
