### ISSUE TITLE
Pass option { overwrite: true } to mergeTrees in order to have the latter file win

### ISSUE THREAD

**Issue by RobIsHere** [mydea/ember-date-components#7]
I have also Ember Power Select installed, v0.10.11

**Comment by mydea** [comment]
Hey, what exactly is the problem here?

**Comment by RobIsHere** [comment]
It looks like ember-basic-dropdown is included twice. Then ember cli fails to build with the error above.

I switched to ember-power-calendar and that solved it for me. They also include dropdown. Sorry! Tough timeline, had to get ready yesterday  😌

Just wanted to let you know about this problem.

**Comment by mydea** [comment]
I'll close this for now, as I could never really replicate any type of issue here. If this happens again to someone, please feel free to re-open.
