### ISSUE TITLE
.git folder available on npm

### ISSUE THREAD

**Issue by ThemeSama** [mydea/ember-date-components#73]
Hi! Can you check your npmjs registry?
I got this message after ember install.
```
npm ERR! path /node_modules/ember-date-components
npm ERR! code EISGIT
npm ERR! git /node_modules/ember-date-components: Appears to be a git repo or submodule.
npm ERR! git  /node_modules/ember-date-components
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.
```

**Comment by mydea** [comment]
Hi there,

the .git folder should be ignored, but I think this is an issue on npm-side - see: https://npm.community/t/npm-6-9-1-is-broken-due-to-git-folder-in-published-tarball/8454/5

Are you by change on npm 6.9.1? If so, please try updating, see if it works then (if not, please try removing the node_modules folder and re-installing).

**Comment by ThemeSama** [comment]
I get this error with npm 6.10.0. I installed 6.10.2 and problem is solved. Thank you!

**Comment by Parthipan-Natkunam** [comment]
This issue is reproducible in the latest version (2.0.6) of ember-date-components as the package for this version has a .git folder.
https://unpkg.com/browse/ember-date-components@2.0.6/

**Comment by alejandrodevs** [comment]
I am still struggling with this. Any work around?

**Comment by mydea** [comment]
I will cut a release soon with .git explicitly ignored for npm!
