### ISSUE TITLE
Update docs to indicate value=[prop] is required

### ISSUE THREAD

**Issue by andycochran** [mydea/ember-date-components#77]
In trying to figure out why the example usage codes weren't giving me the same results in my app as in the docs, I decided to look at the dummy app to see how they were actually implemented there. I realized that I needed to give the component a `value`. Silly me; I should've figured that out sooner. But would be nice to note this in the docs and usage examples.

**Comment by mydea** [comment]
I have updated the docs accordingly, should hopefully be more explicit now!
