### ISSUE TITLE
Picking a time option has no effect sometimes

### ISSUE THREAD

**Issue by callovarne** [mydea/ember-date-components#8]
In _time-picker_, picking a time option has no effect sometimes. The issue can be seen in the [demos](http://mydea.github.io/ember-date-components/#/usage/time-picker). Seems like a race condition involving the value.

Steps:
1. click the time-picker input
2. click a time option
3. click the time-picker input
4. click a _different_ time option

Expected: time-picker input's value is the value of the option selected the second time
Actual: time-picker input's value is the value of the option selected the first time

Notes: slowing things down, e.g. by adding a console.log() in the _selectValue_ action, seems to make encountering this behavior less probable.

**Comment by mydea** [comment]
Hmm, what I could reproduce right now is that it doesn't seem to be firing when selecting the first option (e.g. 12:00 am). I'll get on to that asap.

**Comment by mydea** [comment]
I just released 1.0.1, which hopefully fixes this. Please get back to me if you still experience issues!
